name = "MyStatsPackage"
uuid = "c532ca38-d4ba-4b3c-bc8c-66066da61c02"
authors = ["aarondanielyphysics <aaron.daniel@unibas.ch>"]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ProgressMeter = "1"
